# Generated by Django 5.0.3 on 2024-05-24 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_accessrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecord',
            old_name='n',
            new_name='name',
        ),
    ]
